#!/bin/bash -l
# declare a name for this job to be sample_job
#PBS -N analys_2_sub01_b

# request the default queue for this job
#PBS -q default

# request a total of 16 processors for this job (1 nodes and 16 processors per
# node)
#PBS -l nodes=1:ppn=16

# mail is sent to you when the job starts and when it terminates or aborts
#PBS -m bea

# specify your email address
#PBS -M andrew.c.connolly@dartmouth.edu

#change to the directory where you submitted the job
#cd $PBS_O_WORKDIR

module load mpich3
module load python/3-Anaconda
cd /dartfs-hpc/rc/home/k/d29262k/ds000233/derivatives/mvpc/code
# include the relative path to the name of your MPI program
mpirun -machinefile $PBS_NODEFILE python analys_2_ROISearch+PP.py 01
